language: cpp

sudo: required
dist: trusty

before_install:
  - ./scripts/travis-before-install.sh
  - export CC=~/bin/cc
  - export CXX=~/bin/cxx
  - ${CC} --version
  - ${CXX} --version

script:
  - autoreconf --install
  - CPPFLAGS='-Werror' ./configure --enable-sound --enable-warnings
  - make
  - ./run-tests
  - make distcheck

matrix:
  include:
    - os: linux
      compiler: clang
      env: CLANG_VERSION=3.5
    - os: linux
      compiler: clang
      env: CLANG_VERSION=3.6
    - os: linux
      compiler: clang
      env: CLANG_VERSION=3.7
    - os: linux
      compiler: clang
      env: CLANG_VERSION=3.8
    - os: linux
      compiler: gcc
      env: GCC_VERSION=4.8
    - os: linux
      compiler: gcc
      env: GCC_VERSION=4.9
    - os: linux
      compiler: gcc
      env: GCC_VERSION=5

    - os: osx
      compiler: clang
    - os: osx
      compiler: gcc
